<?php

/**
 * @file sif.module
 * Main module file for SIF Integration
 */


/**
 * Implements hook_permission().
 */
function sif_permission() {
  $permissions = array(
    'configure sif' => array(
      'title' => t('Configure SIF'),
      'description' => t('Allows users to configure SIF server settings.'),
      'restrict access' => TRUE,
    ),
  );

  return $permissions;
}


/**
 * Helper for generating our application key.
 */
function sif_get_application_key(){
  $token = variable_get('sif_server_auth_token', 'new');
  $secret = variable_get('sif_server_auth_secret', 'guest');
  return "Basic " . base64_encode($token . ':' . $secret);
}


/**
 * Helper to get human readable XML
 */
function clean_xml($xml){
  $simpleXml = new SimpleXMLElement($xml);
  $dom = dom_import_simplexml($simpleXml)->ownerDocument;
  $dom->formatOutput = true;
  return $dom->saveXML();
}
