<?php

/**
 * @file
 * Provides a storage for SIF Data Objects.
 */
function sif_data_object_entity_info() {
  $return = array(
    'sif_data_object' => array(
      'label' => t('SIF Data Object'),
      'controller class' => 'SifEntityAPIController',
      'base table' => 'sif_data_object',
      'uri callback' => 'sif_object_uri',
      'entity keys' => array(
        'id' => 'id',
        'bundle' => 'type',
      ),
      'bundle keys' => array(
        'bundle' => 'name',
      ),
      'bundles' => array(),
      'view modes' => array(
        'preview' => array(
          'label' => t('Data Preview'),
        ),
        'xml' => array(
          'label' => t('Raw XML'),
        ),
      ),
    ),
  );

  $objects = module_invoke_all('sif_data_object_types');
  foreach ($objects as $type => $name) {
    $return['sif_data_object']['bundles'][$type] = array(
      'label' => $name,
      'admin' => array(
        'path' => 'admin/sif/objects/%type',
        'real path' => 'admin/sif/objects/' . $type,
        'bundle argument' => 3,
        'access arguments' => array('configure sif'),
      ),
    );
  }
  return $return;
}

/**
 * Implements hook_sif_data_object_types()
 */
function sif_data_object_sif_data_object_types(){
  return array(
    'environment' => t('Environment'),
    'zone' => t('Zone'),
    'queue' => t('Queue'),
    'subscription' => t('Subscription'),
    'alert' => t('Alert'),
    'student' => t('Student'),
  );
}

/**
 * Delete Sif Object
 */
function sif_data_object_delete($sif_id, $delete_from_server = FALSE){

  // First send a DELETE message to the server
  if ($delete_from_server){
    // POST this environment XML
    $url = variable_get('sif_server', 'http://rest3api.sifassociation.org/api');
    $url .= '/environments/environment';

    $options = array(
      'method' => 'POST',
      'data' => $form_state['values']['xml'],
      'headers' => array(
        'Authorization' => sif_get_application_key(),
        'Accept' => 'application/xml',
        'Content-Type' => 'application/xml',
      ),
    );
    $response = drupal_http_request($url, $options);

    if ($response->code != "201"){
      form_set_error('xml', t('POST unsuccessful: !message', array('!message' => strip_tags($response->data))));
    }
    else {
      form_set_value($form['xml'], $response->data, $form_state);
    }

  }

    // Then, delete the local entity
    //entity_delete('sif_data_object', $sif->id);

}
