<?php
/**
 * @file
 * sif_subscriptions.module
 */

/**
 * Implements hook_menu().
 */
function sif_subscriptions_menu() {
  $items = array();
  $items['admin/sif/subscriptions'] = array(
    'title' => 'Subscriptions',
    'description' => 'Create and manage SIF subscriptions.',
    'page callback' => 'sif_subscriptions_page',
    'access arguments' => array('configure sif'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages.inc',
  );
  $items['admin/sif/subscriptions/create'] = array(
    'title' => 'Create Subscription',
    'description' => 'Create a new subscription.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sif_subscriptions_create'),
    'access arguments' => array('configure sif'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'pages.inc',
  );
  $items['admin/sif/subscriptions/get'] = array(
    'title' => 'Get or Update Subscriptions',
    'description' => 'Load all subscriptions from the SIF server.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sif_subscriptions_get'),
    'access arguments' => array('configure sif'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'pages.inc',
  );

  return $items;
}
