<?php

/**
 * @file
 * Defines menu items common to the various Drupal Commerce UI modules.
 */


/**
 * Implements hook_menu().
 */
function sif_ui_menu() {
  $items = array();
  $items['admin/sif'] = array(
    'title' => 'SIF',
    'description' => 'Administer SIF.',
    'page callback' => 'system_admin_menu_block_page',
    'access arguments' => array('access administration pages'),
    'file path' => drupal_get_path('module', 'system'),
    'file' => 'system.admin.inc',
    'weight' => -7,
  );
  $items['admin/sif/config'] = array(
    'title' => 'SIF Server',
    'description' => 'Configure the SIF Server and authentication.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sif_settings_form'),
    'access arguments' => array('configure sif'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/settings.inc',
  );
  $items['admin/sif/environments'] = array(
    'title' => 'Environments',
    'description' => 'Create and manage SIF environments.',
    'page callback' => 'sif_ui_environments',
    'access arguments' => array('configure sif'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/environments.inc',
  );
  $items['admin/sif/environments/create'] = array(
    'title' => 'Create Environment',
    'description' => 'Create a new environment.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sif_ui_environment_create'),
    'access arguments' => array('configure sif'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'includes/environments.inc',
  );
  $items['admin/sif/types'] = array(
    'title' => 'Data Object Types',
    'description' => 'Manage the SIF Data Object Types.',
    'page callback' => 'sif_ui_data_object_types',
    'access arguments' => array('configure sif'),
    'file' => 'includes/types.inc',
  );
  // SIF Object View page.
  $items['sif/%sif_object'] = array(
    'title callback' => 'entity_label',
    'title arguments' => array('sif_data_object', 1),
    'page callback' => 'sif_object_view_page',
    'page arguments' => array(1),
    'access callback' => 'sif_object_access',
    'access arguments' => array('view', 1),
    'file' => 'includes/pages.inc',
  );
  $items['sif/%sif_object/details'] = array(
    'title' => 'Details',
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
  );
  $items['sif/%sif_object/xml'] = array(
    'title' => 'XML',
    'page callback' => 'sif_object_view_page',
    'page arguments' => array(1, 2),
    'access callback' => 'sif_object_access',
    'access arguments' => array('view', 1),
    'file' => 'includes/pages.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['sif/%sif_object/delete'] = array(
    'title' => 'Delete',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sif_object_delete_form', 1),
    'access callback' => 'sif_object_access',
    'access arguments' => array('delete', 1),
    'weight' => 1,
    'type' => MENU_LOCAL_TASK,
    'context' => MENU_CONTEXT_PAGE | MENU_CONTEXT_INLINE,
    'file' => 'includes/pages.inc',
  );
  $items['sif/%/service/%/view'] = array(
    'title' => 'Service View',
    'description' => 'View Environment Services',
    'page callback' => 'sif_service_view',
    'page arguments' => array(1, 3),
    'access arguments' => array('configure sif'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/pages.inc',
  );

  // Optional devel module integration
  if (module_exists('devel')) {
    $items['sif/%sif_object/devel'] = array(
      'title' => 'Devel',
      'page callback' => 'devel_load_object',
      'page arguments' => array('sif_data_object', 1),
      'access arguments' => array('access devel information'),
      'type' => MENU_LOCAL_TASK,
      'file' => 'devel.pages.inc',
      'file path' => drupal_get_path('module', 'devel'),
      'weight' => 100,
    );
  }
  return $items;
}

/**
 *
 */
function sif_object_load($sif_id) {
  $sif_entities = sif_object_load_multiple(array($sif_id), array());
  return reset($sif_entities);
}

/**
 *
 */
function sif_object_load_multiple($sif_ids = array(), $conditions = array()) {
  return entity_load('sif_data_object', $sif_ids, $conditions);
}

/**
 *
 */
function sif_object_access($action = 'view', $sif){
  return user_access('configure sif');
}
