<?php
/**
 * @file
 * sif_queues.module
 */

/**
 * Implements hook_menu().
 */
function sif_queues_menu() {
  $items = array();
  $items['admin/sif/queues'] = array(
    'title' => 'Queues',
    'description' => 'Create and manage SIF queues.',
    'page callback' => 'sif_queues_page',
    'access arguments' => array('configure sif'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'pages.inc',
  );
  $items['admin/sif/queues/create'] = array(
    'title' => 'Create Queue',
    'description' => 'Create a new queue.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sif_queues_create'),
    'access arguments' => array('configure sif'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'pages.inc',
  );
  $items['admin/sif/queues/get'] = array(
    'title' => 'Get or Update Queues',
    'description' => 'Load all queues from the SIF server.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sif_queues_get'),
    'access arguments' => array('configure sif'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'pages.inc',
  );


  // SIF Object View page.
  $items['sif/%sif_object/messages'] = array(
    'title' => 'Messages',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sif_queues_get_messages', 1),
    'access callback' => 'sif_queues_menu_access',
    'access arguments' => array(1),
    'file' => 'includes/pages.inc',
    'type' => MENU_LOCAL_TASK,
    'file' => 'messages.inc',
  );

  // Subscriptions
  $items['admin/sif/%/subscriptions'] = array(
    'title' => 'Subscriptions',
    'description' => 'Create and manage SIF subscriptions.',
    'page callback' => 'sif_subscriptions_page',
    'page arguments' => array(2),
    'access arguments' => array('configure sif'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'subscriptions.inc',
  );
  $items['admin/sif/%/subscriptions/create'] = array(
    'title' => 'Create Subscription',
    'description' => 'Create a new subscription.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sif_subscriptions_create', 2),
    'access arguments' => array('configure sif'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'subscriptions.inc',
  );
  $items['admin/sif/%/subscriptions/get'] = array(
    'title' => 'Get or Update Subscriptions',
    'description' => 'Load all subscriptions from the SIF server.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('sif_subscriptions_get', 2),
    'access arguments' => array('configure sif'),
    'type' => MENU_LOCAL_ACTION,
    'file' => 'subscriptions.inc',
  );
  return $items;
}

/**
 *  Only show up on queues.
 */
function sif_queues_menu_access($sif_object){
  return $sif_object->type == 'queue';
}
